### ISSUE TITLE
spp模块连接自拍杆，搜到了mac，但是点击总出现，断开连接

### ISSUE THREAD

**Issue by hsf25737** [arpsyalin/BluetoothUtils#2]

**Comment by arpsyalin** [comment]
你可以看看是否是因为UUID的问题。createRfcommSocketToServiceRecord的时候会创建一个UUID，我这里默认使用的是SPP串口服务，SppManage.getInstance().setUUID(你的UUID);

**Comment by arpsyalin** [comment]
你可以参考CONSTANT_UUID.java类
